name: release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Select semver increment"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install semver
        run: npm install -g semver

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$LATEST_TAG" ]]; then
            LATEST_TAG="0.0.0"
          fi
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Calculate next version
        id: next_version
        run: |
          NEXT_TAG=$(npx semver ${LATEST_TAG} -i ${{ github.event.inputs.increment }})
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
          echo "next_tag=$NEXT_TAG" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        run: |
          if git rev-parse "refs/tags/${NEXT_TAG}" >/dev/null 2>&1; then
            echo "Tag ${NEXT_TAG} already exists. Exiting."
            exit 1
          fi

      - name: Create GitHub Release
        run: |
          gh release create $NEXT_TAG --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
