name: Delete Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Tag of the release to delete"
        required: true
        type: string

jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete Release
        run: |
          if gh release view ${{ github.event.inputs.release_tag }} > /dev/null 2>&1; then
            echo "Deleting release ${{ github.event.inputs.release_tag }}..."
            gh release delete ${{ github.event.inputs.release_tag }} -y
          else
            echo "Release ${{ github.event.inputs.release_tag }} does not exist. Skipping."
          fi

      - name: Delete Associated Tag
        run: |
            git fetch --tags
            if git rev-parse ${{ github.event.inputs.release_tag }} > /dev/null 2>&1; then
              echo "Deleting tag ${{ github.event.inputs.release_tag }}..."
              git tag -d ${{ github.event.inputs.release_tag }}
              git push origin --delete ${{ github.event.inputs.release_tag }}
            else
              echo "Tag ${{ github.event.inputs.release_tag }} does not exist. Skipping."
            fi
  