name: Delete Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Tag of the release to delete"
        required: true
        type: string

jobs:
  delete-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete Release
        run: gh release delete ${{ github.event.inputs.release_tag }} -y

      - name: Delete Associated Tag
        run: |
            git tag -d ${{ github.event.inputs.release_tag }}
            git push origin --delete ${{ github.event.inputs.release_tag }}
